version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: crud_db
      DB_USER: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: crud_db
      MYSQL_ROOT_PASSWORD: root
      TZ: "America/Argentina/Buenos_Aires"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: my_db_container
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2g'

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9002:80"
    environment:
      - PMA_ARBITRARY=1
    container_name: my_phpmyadmin_container


volumes:
  db_data:
