version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_NAME=prueba-crud
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba-crud
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
